export type AppStackParamList = {
  BenchmarkBaseText: undefined;
  BenchmarkIndex: undefined;
  BenchmarkMeasuredLayoutCaseStudy: undefined;
  BenchmarkPretextLayout: undefined;
  ExampleIndex: undefined;
  ExampleMeasuredLayout: undefined;
  ExampleNoneUseCaseDiagnostics: undefined;
  ExampleNoneUseCaseHook: undefined;
  ExampleNoneUseCaseIndex: undefined;
  ExampleNoneUseCaseLayoutLines: undefined;
  ExampleNoneUseCaseLayoutMetrics: undefined;
  ExampleNoneUseCaseLayoutOptions: undefined;
  ExampleNoneUseCaseLayoutRich: undefined;
  ExampleNoneUseCasePrepare: undefined;
  ExampleUseCaseDiagnostics: undefined;
  ExampleUseCaseHook: undefined;
  ExampleUseCaseIndex: undefined;
  ExampleUseCaseLayoutLines: undefined;
  ExampleUseCaseLayoutMetrics: undefined;
  ExampleUseCaseLayoutOptions: undefined;
  ExampleUseCaseLayoutRich: undefined;
  ExampleUseCaseNamespaceAndTypes: undefined;
  ExampleUseCasePrepare: undefined;
  Home: undefined;
};
